from selenium import webdriver
from selenium.webdriver.common.by <http://selenium.webdriver.common.by/> import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select 
browser = webdriver.Chrome()
shoeSize = browser.find_element_by_css_selector("#buyTools > div:nth-child(1) > div > label:nth-child(7)")
shoeSize.click()
addCart = browser.find_element_by_xpath("""//*[@id="buyTools"]/div[2]/button[1]""")
addCart.click()
wait = WebDriverWait(browser, 10)
wait.until(EC.presence_of_element_located((By.XPATH, """//*[@id="PDP"]/div/div[3]/div/div/div/div/div/div/div/div/div/div[3]/button""")))
viewCart = browser.find_element_by_xpath("""//*[@id="PDP"]/div/div[3]/div/div/div/div/div/div/div/div/div/div[3]/button""")
viewCart.click()
checkOutButton = browser.find_element_by_xpath("""//*[@id="ch4_cartCheckoutBtn"]""")
checkOutButton.click()
wait.until(EC.presence_of_element_located((By.XPATH, """//*[@id="qa-guest-checkout"]""")))
guestCheckout = browser.find_element_by_xpath("""//*[@id="qa-guest-checkout-mobile"]""")
guestCheckout.click()
wait.until(EC.presence_of_element_located((By.ID,"firstName")))
enterFirstName = browser.find_element_by_id("firstName")
enterFirstName.send_keys(“enterFirstName”)
enterLastName = browser.find_element_by_id("lastName")
enterLastName.send_keys(“enterLastName”)
enterAddress = browser.find_element_by_id("address1")
enterAddress.send_keys(“enterAddress”)
enterCity = browser.find_element_by_id("city")
enterCity.send_keys("Quincy")
select = Select(browser.find_element_by_id("state")).select_by_value("MA").click()
enterCode = browser.find_element_by_id("postalCode")
enterCode.send_keys("02169")
enterEmail = browser.find_element_by_id("email")
enterEmail.send_keys("enterEmail")
enterPhone = browser.find_element_by_id("phoneNumber")
enterPhone.send_keys(“enterNumber”)
shippingContinue = browser.find_element_by_xpath("""//*[@id="shipping"]/div/div/div/form/div/div/div/div[2]/button""")
shippingContinue.click()
wait.until(EC.presence_of_element_located((By.XPATH, """//*[@id="shipping"]/div/div/div/div[5]/button""")))
continuePayment = browser.find_element_by_xpath("""//*[@id="shipping"]/div/div/div/div[5]/button""")
continuePayment.click()
wait.until(EC.presence_of_element_located((By.XPATH, """//*[@id="payment"]/div/div/div[2]/div[4]/div/div/div[1]/div[2]/iframe""")))
boxFrame = browser.find_element_by_xpath("""//*[@id="payment"]/div/div/div[2]/div[4]/div/div/div[1]/div[2]/iframe""")
browser.switch_to.frame(boxFrame)
cardNumber = browser.find_element_by_id("creditCardNumber")
cardNumber.send_keys("enterCard")
expirationDate = browser.find_element_by_id("expirationDate")
expirationDate.send_keys("enterDate")
securityCode = browser.find_element_by_id("cvNumber")
securityCode.send_keys("enterCv")
browser.switch_to_default_content()
continueOrderReview = browser.find_element_by_xpath("""//*[@id="payment"]/div/div/div[2]/div[5]/button""")
continueOrderReview.click()
placeOrder = browser.find_element_by_xpath("""//*[@id="place-order"]/div/button""")
placeOrder.click()
exit()